version: 2
updates:
  - package-ecosystem: npm
    directory: /pages
    schedule:
      interval: weekly
    groups:
      pages-dependencies:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /worker
    schedule:
      interval: weekly
    groups:
      worker-dependencies:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
